environment:

  matrix:
    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.4.4"
      PYTHON_ARCH: "32"
      QTIMPL: "PyQt4"
      INSTALL_QT: "py34-pyqt4"
      TESTENVS: "py34-pyqt4"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH% %QTIMPL%"

install:
  - "C:\\Python34\\python -u appveyor\\install_qt.py"
  - "powershell appveyor\\install.ps1"
  - ps: "$env:APPVEYOR_BUILD_VERSION = (& c:\\Python34\\python .\\src\\config\\version.py) + \"+\" + $env:APPVEYOR_BUILD_NUMBER"
  - ps: "get-childitem env:"
  - ps: "$env:PYTEST_QT_API=\"pyqt4\""
  - ps: "$env:FAF_FORCE_PRODUCTION=true"
  - "%PYTHON%\\Scripts\\pip.exe install -r requirements.txt --trusted-host content.faforever.com"

test_script:
    - "%PYTHON%\\Scripts\\py.test.exe -vv --full-trace"

after_test:
  - "%PYTHON%\\python setup.py bdist_msi"

artifacts:
  - path: '**\*.msi'

deploy:
  - provider: GitHub
    release: $(appveyor_build_version)
    auth_token:
      secure: "09WRxoB8lu9lPzuk3qYu0brKVQubLpnsS1Wdn49nYZYi5RDiva3z37eITcjtZkTD"
    artifact: /.*\.msi/
    draft: true
    prerelease: true
    on:
      branch: develop

  - provider: GitHub
    release: $(appveyor_build_version)
    auth_token:
      secure: "09WRxoB8lu9lPzuk3qYu0brKVQubLpnsS1Wdn49nYZYi5RDiva3z37eITcjtZkTD"
    artifact: /.*\.msi/
    draft: false
    prerelease: false
    on:
      branch: master
      appveyor_repo_tag: true

build: off
